### ISSUE TITLE
Unit-Test Configuration

### ISSUE THREAD

**Issue by jgxvx** [FFHS-Inf-2010-students/Lifeguard#12]
Testcases mal grün machen.
- ConfigurationTest
- ConfigurationsTest

**Comment by ckpinguin** [comment]
Configuration ist nur für delay (Spaltenname) ausgelegt, wäre es nicht sinnvoller mit einer Spalte "item" zu arbeiten, damit später evtl. auch andere configuration-items in der Tabelle abgelegt werden können? Ich versuche dies mal so zu implementieren, wenn niemand was dagegen hat.

**Comment by jgxvx** [comment]
Ich bin mir nicht sicher, wie das unsere Situation verbessern würde? Welche Werte würden dann in der item-Spalte gespeichert?
Momentan ist es so, dass es für jedes Konfigurationselement eine Spalte gibt (momentan effektiv nur «delay»). Das bedeutet natürlich, dass bei jedem neuen Konfigurationselement eine neue Spalte eingeführt werden müsste. Da aber nicht von einem starken Ansteigen von Konfigurationselementen auszugehen ist, halte ich das persönlich nicht für allzu problematisch.

**Comment by ckpinguin** [comment]
OK, das reicht mir schon, ich dachte eben an etwas generisches mit Spalten "item" "int_value" "string_value" oder so, aber eine Spalte pro Conf-item ist mir genauso recht (eigentlich eher einfacher). Thanks!
