### ISSUE TITLE
Unit-Test Configurations

### ISSUE THREAD

**Issue by ckpinguin** [FFHS-Inf-2010-students/Lifeguard#19]
erst nach Refactoring der Speicherung via XML anstatt DB

**Comment by jgxvx** [comment]
Ich teste im ConfigurationActivityTest bereits das korrekte Laden und Speichern (via UI). Ich weiss nicht, ob es noch einen gesonderten Configuration(s)-Test braucht. Meines Erachtens ist die Funktionalität bereits abgedeckt.

ETA: Die alten Configuration(s)-Klassen und -Interfaces, sowie die dazugehörigen Tests habe ich bereits gelöscht.

**Comment by ckpinguin** [comment]
Mal etwas aufräumen nach langer Zeit :-)
