### ISSUE TITLE
Als Hilfsbedürftiger kann ich die Auslösedauer definieren (UC5)

### ISSUE THREAD

**Issue by jgxvx** [FFHS-Inf-2010-students/Lifeguard#2]

**Comment by jgxvx** [comment]
Domain: Configuration

**Comment by ckpinguin** [comment]
Refactoring, dass Preferences analog Beispielen PVA4 anstatt in der DB gespeichert werden

**Comment by jgxvx** [comment]
Da die Konfiguration ja nun mit den Android-Klassen verwaltet wird, kann ch.ffhs.esa.lifeguard.domain.Configuration\* eigentlich gelöscht werden, oder?

**Comment by ckpinguin** [comment]
Ich würde sagen ja, ich werde es alsbald löschen, Du musst da vorerst nichts machen. Wünsche schon schöne Festtage :-) Gruess Chrigi From: Jürg Gutknecht (notifications@github.com) Sent: Sunday, December 15, 2013 10:56 PM To: FFHS-Inf-2010-students/Lifeguard (Lifeguard@noreply.github.com) Cc: Christof Kälin (christof.kaelin@gmail.com) Subject: Re: [Lifeguard] Als Hilfsbedürftiger kann ich die Auslösedauer definieren (UC5) (#2)   Da die Konfiguration ja nun mit den Android-Klassen verwaltet wird, kann ch.ffhs.esa.lifeguard.domain.Configuration\* eigentlich gelöscht werden, oder? — Reply to this email directly or view it on GitHub.

**Comment by ckpinguin** [comment]
Mal etwas aufräumen nach langer Zeit :-)
